optimizer:
  name: "Lookahead"
  params:
    base:
      name: "RAdam"
      params:
        lr: 5e-03
        weight_decay: 1e-6
    k: 5
    alpha: 0.5

scheduler:
  name: "CosineAnnealingLR"
  params:
    T_max: 3
    eta_min: 1e-6
