optimizer:
  name: "SAM"
  params:
    base:
      name: "RAdam"
      params:
        lr: 5e-03
    weight_decay: 1e-6
    rho: 0.1
    adaptive: True

scheduler:
  name: "CosineAnnealingLR"
  params:
    T_max: 3
    eta_min: 1e-6
