# image size
height:
width:

# augmentation inside dataset
transform:
  train:
    - name: RandomResizedCrop
      params:
        p: 1.0
        scale: [0.875, 1.0]
        height: 256
        width: 256
  validation:
    - name: Resize
      params:
        p: 1.0
        height: 256
        width: 256
  test:
    - name: Resize
      params:
        p: 1.0
        height: 256
        width: 256

# augmenatation like mixup
strong_transform:
#   name: mixup
#   params:
#     p: 0.5
#     alpha: 0.8

# augmentation on torch.Tensor
batch_transform:
  train:

  validation:

  test:

# TTA
tta_transform:
#   _target_: ttach.ClassificationTTAWrapper
#   transforms:
#     _target_: ttach.aliases.d4_transform
#   merge_mode: 'mean'
